//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorClient.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.ICalculatorService")]
    public interface ICalculatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/GetText", ReplyAction="http://tempuri.org/ICalculatorService/GetTextResponse")]
        string GetText(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/GetText", ReplyAction="http://tempuri.org/ICalculatorService/GetTextResponse")]
        System.Threading.Tasks.Task<string> GetTextAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/GetName", ReplyAction="http://tempuri.org/ICalculatorService/GetNameResponse")]
        string GetName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/GetName", ReplyAction="http://tempuri.org/ICalculatorService/GetNameResponse")]
        System.Threading.Tasks.Task<string> GetNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/AddIntegerNumbers", ReplyAction="http://tempuri.org/ICalculatorService/AddIntegerNumbersResponse")]
        int AddIntegerNumbers(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/AddIntegerNumbers", ReplyAction="http://tempuri.org/ICalculatorService/AddIntegerNumbersResponse")]
        System.Threading.Tasks.Task<int> AddIntegerNumbersAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/SubtractIntegerNumbers", ReplyAction="http://tempuri.org/ICalculatorService/SubtractIntegerNumbersResponse")]
        int SubtractIntegerNumbers(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/SubtractIntegerNumbers", ReplyAction="http://tempuri.org/ICalculatorService/SubtractIntegerNumbersResponse")]
        System.Threading.Tasks.Task<int> SubtractIntegerNumbersAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/DivideIntegerNumbers", ReplyAction="http://tempuri.org/ICalculatorService/DivideIntegerNumbersResponse")]
        int DivideIntegerNumbers(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/DivideIntegerNumbers", ReplyAction="http://tempuri.org/ICalculatorService/DivideIntegerNumbersResponse")]
        System.Threading.Tasks.Task<int> DivideIntegerNumbersAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/GetRequests", ReplyAction="http://tempuri.org/ICalculatorService/GetRequestsResponse")]
        int GetRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/GetRequests", ReplyAction="http://tempuri.org/ICalculatorService/GetRequestsResponse")]
        System.Threading.Tasks.Task<int> GetRequestsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorServiceChannel : CalculatorClient.CalculatorService.ICalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<CalculatorClient.CalculatorService.ICalculatorService>, CalculatorClient.CalculatorService.ICalculatorService {
        
        public CalculatorServiceClient() {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetText(string value) {
            return base.Channel.GetText(value);
        }
        
        public System.Threading.Tasks.Task<string> GetTextAsync(string value) {
            return base.Channel.GetTextAsync(value);
        }
        
        public string GetName(string name) {
            return base.Channel.GetName(name);
        }
        
        public System.Threading.Tasks.Task<string> GetNameAsync(string name) {
            return base.Channel.GetNameAsync(name);
        }
        
        public int AddIntegerNumbers(int num1, int num2) {
            return base.Channel.AddIntegerNumbers(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> AddIntegerNumbersAsync(int num1, int num2) {
            return base.Channel.AddIntegerNumbersAsync(num1, num2);
        }
        
        public int SubtractIntegerNumbers(int num1, int num2) {
            return base.Channel.SubtractIntegerNumbers(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> SubtractIntegerNumbersAsync(int num1, int num2) {
            return base.Channel.SubtractIntegerNumbersAsync(num1, num2);
        }
        
        public int DivideIntegerNumbers(int num1, int num2) {
            return base.Channel.DivideIntegerNumbers(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> DivideIntegerNumbersAsync(int num1, int num2) {
            return base.Channel.DivideIntegerNumbersAsync(num1, num2);
        }
        
        public int GetRequests() {
            return base.Channel.GetRequests();
        }
        
        public System.Threading.Tasks.Task<int> GetRequestsAsync() {
            return base.Channel.GetRequestsAsync();
        }
    }
}
